apiVersion: v1
kind: Service
metadata:
  name: btfs
  labels:
    app: btfs
spec:
  ports:
  - name: web-ui
    port: 5001
  - name: unknown-8080
    port: 8080
  - name: unknown-2345
    port: 2345
  - name: unknown-2346
    port: 2346
  clusterIP: None
  selector:
    app: btfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btfs
spec:
  serviceName: "btfs"
  replicas: 2
  selector:
    matchLabels:
      app: btfs
  template:
    metadata:
      labels:
        app: btfs
    spec:
      containers:
      - name: btfs
        # image: harbor.degital.io/dedrive-node/btfs_node
        image: louolkol/btfs
        ports:
        - containerPort: 5001
          name: ui
        - containerPort: 8080
          name: unknown-8080
        - containerPort: 2345
          name: unknown-2345
        - containerPort: 2346
          name: unknown-2346
        volumeMounts:
        - name: btfs-volume
          mountPath: /data/btfs
        resources:
          requests:
            cpu: 1
            memory: 2048M
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 220
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: btfs-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-gp2
      resources:
        requests:
          storage: 1Gi